### ISSUE TITLE
Wrong number of samples read by openWorkspace

### ISSUE THREAD

**Issue by JC203** [RGLab/flowWorkspace#245]
When I open my workspace with 16 samples in total it tell me that my other groups also contain 16 samples which is not the case. This gives multiplied SampleIDs and therefore I can't parse the workspace. I'm using the newest version of FlowJo (10.4.2) and R 3.4.4.

Print of workspace
``` 
FlowJo Workspace Version  20.0 
File location:  data 
File name:  27-Mar-2018 TNAP-YFP D10.wsp 
Workspace is open. 

Groups in Workspace
          Name Num.Samples
1  All Samples          16
2 Compensation          16
3       Sample          16
```

Error thrown by parseWorkspace:
```
Error in .parse.pData(obj = obj, keywords = keywords, sg = sg, keywords.source = keywords.source, : duplicated samples ID within group: 1 2 3 4 5 21 22 23 24 25
```

**Comment by gfinak** [comment]
What group are you trying to parse? You can only parse one sample group into a gating set. In this case you should parse the "Sample" group, by passing name=3 to parseWorkspace . You didn't include your parseWorkspace call.. so I'm just guessing here.

**Comment by JC203** [comment]
`(gs <- parseWorkspace(ws, name = 3))`
Error in .parse.pData(obj = obj, keywords = keywords, sg = sg, keywords.source = keywords.source, : duplicated samples ID within group: 1 2 3 4 5 21 22 23 24 25

**Comment by JC203** [comment]
I was parsing the Sample group, the openWorkspace function just duplicates samples because I have 16 samples in total, 6 in compensation and 10 in Sample

**Comment by gfinak** [comment]
I see, thanks. This clearly a bug. Can you share the workspace?

**Comment by JC203** [comment]
I send you an email with the workspace attached

**Comment by gfinak** [comment]
Thanks.

**Comment by mikejiang** [comment]
found the cause
![image](https://user-images.githubusercontent.com/1385649/38048518-72ea9f80-327a-11e8-8cff-98a4d1f9b0da.png)
Here in this workspace `Group` node has an extra subgroup `ManuallyIncludedSamples`, which refers to the identical set of sampleIDs as `SampleRefs`. 
Typically we only have `SampleRefs` subgroup thus we do the generic xpath searching through `GroupNode//SampleRef` to collect all sampleIDs.
Looks like the `xpath` needs to be more specific in this case.

**Comment by mikejiang** [comment]
I've pushed the fix to both bioc release and devel branches.

**Comment by JC203** [comment]
Updating via biocLite doesn't fix the problem for me and devtools install_github command is throwing an error...

**Comment by SamGG** [comment]
The fix is available on github, not bioclite yet.  I think you should report the error you get in order that Mike or Greg could solve it.

**Comment by JC203** [comment]
Could it be that is has anything to do with the version of cytolib? I have version 1.0.1 (bioconductor) while it says I should have 1.1.13 to install flowWorkspace from github. Problem is it's only on bioconductor 3.7 and then data.table fails in R 3.5 so it seems I'm not able to run it

**Comment by mikejiang** [comment]
To install from the github trunk, Your will need bioc devel (i.e. 3.7). If you want to stick to bioc release, you will have to wait until its daily build cycle finishes (should be done by later this afternoon).

**Comment by gfinak** [comment]
Or use the bioconductor repository directly:
Clone:
`git clone git@git.bioconductor.org:packages/flowWorkspace`

checkout the release branch:
`git checkout -b RELEASE_3_6`

And install from it:
`R CMD INSTALL flowWorkspace --preclean`

repeat as necessary with other release branch packages.
