### ISSUE TITLE
Function to subset a flowFrame with indices instead of gates

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/flowWorkspace#259]
Hello!

I was wondering if there is a way to remove some of the events, without using the gates. i.e., Running flowCut/flowClean, gives me indices of bad cells, and I'd like to remove them in my gatingSet, rather than saving the cleaned FCS files, and use those to create my gatingSet. 
This will be really useful for us, and it might be already implemented inside flowWorkspace, but I couldn't find any based on the manual.

Best,

Mehrnoush

**Comment by gfinak** [comment]
You can add a gate to the GatingSet using the cell indices as we do [here](http://rglab.org/CytoML/) in the section: "Combining manual analysis with high dimensional clustering". 
There, `cluster_assignments` is a list of vectors where each vector has  `length(ncells)` and the list is `length(nsamples)`. The list is named using `sampleNames()`. Each vector is a factor where the levels correspond to cluster membership of each cell. In your case, you could use 0/1 to indicate in or not in the "clean" set of cells. This list is added to the `GatingSet` using the `add` API. 
You can then just call `getData()` to retrieve the cleaned cells from the GatingSet.
This is a relatively new feature so pull the latest GitHub versions of packages (I don't think it's in the BioC release yet).

**Comment by mehrnoushmalek** [comment]
Thanks Greg and Mike!
I updated the flowWorkspace, and works perfectly, just two things, when I  call getData, it will grab the cells that are labelled 1 in cluster_assignment vector right?
I called the node," flowCut", but the getNodes called it 'flowCut_1", not that it matters, I just want to make sure I didn't do anything wrong.

**Comment by mikejiang** [comment]
If you add it as a `logical` vector instead of `factor`, then it won't append the numeric suffix to the node name (because the `factor` is interpreted as clustering labels and potentially will be split into multiple nodes)

**Comment by mehrnoushmalek** [comment]
Amazing, thanks you so much Mike!

**Comment by mehrnoushmalek** [comment]
Dear Mike  and Greg,

I have problem updating the gatingSet, as I have the error of "nodes are not identical accross samples".
This is due to the fact that some samples are clean, so when creating the clustering factor list, some samples have nodes Clean_1, and Clean_0, and some only have Clean_0.
This will cause error when I want to add another node after this.
For now I just assign 1 cell to Clean_1, when all cells are clean, but is there a better way/hack rather than losing 1 cell?

Thanks in advance,
Mehrnoush

**Comment by mikejiang** [comment]
Always include both labels in your factor vector should do it, e.g.
```r
levels(vec) <- c("Clean_0", "Clean_1")
```
this will result in two population nodes and even when one is empty.

**Comment by mehrnoushmalek** [comment]
Thank you Mike!

**Comment by mehrnoushmalek** [comment]
Hello Mike,

Sorry for reopening this issue. I have problem parsing the flowJo workspaces after the automated analysis is done. I put all csv, WSP, and FCS files  in a same folder, and I get error that it cannot use the csv files. Is there another arguments that I have to set when I have the clusters membership csv files?
I tried to check greg's link, but it's not working anymore.

Thanks,

**Comment by gfinak** [comment]
Aw crud. We redirected rglab.org to our new research page, and completely forgot the software pages.

**Comment by gfinak** [comment]
@mehrnoushmalek I've update the link..

**Comment by mehrnoushmalek** [comment]
Thanks Greg, I checked Mike's comment regarding cytoML as well, and it doesn't seem that extra parameters should be passed. I either get this error of : ```
Error in .cpp_gating(gs@pointer, mat, guid, gains, nodeInd, recompute,  : 
  Clean.Margin not found in flowData!
```
or 
`Error in FUN(X[[i]], ...) : Error in readFCSheader(con) : 
  This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file` When put csv files in a same folder as wSP and FCS files.

**Comment by gfinak** [comment]
Can you clarify what `csv` file you're talking about here? This issue was about subsetting with indices. What are you trying to do now? Can you post some code?

**Comment by mehrnoushmalek** [comment]
Dear @mikejiang  and @gfinak,  Is it something related to me using the cluster node as a parent population to  another population (i.e., using ```fs.clean``` to add CD3 to the gating set and so on)? Cause flowJo shows everything fine up to that cluster node, and after that everything seems to be empty.
Also as I mentioned, I cannot open and parse the automated wsp saved by ```GatingSet2flowJo()```, due to csv of of cluster membership within the same path as FCS files.

**Comment by gfinak** [comment]
If you don't add any children to `Clean_0` does it display correctly? And what about `Clean_1`? Does it have children? If not, does it display correctly?

**Comment by gfinak** [comment]
@mehrnoushmalek do you call `recompute` after adding new populations?

**Comment by mehrnoushmalek** [comment]
Yes, I call ```recompute``` after adding each population. And all children go under Clean_0, Clean_1 would be cells that had a bad time parameters, so it doesn't have any children.
What is the problem with ```parseWorkspace()``` giving error I mentioned earlier?
I will check the Clean_1 and see if it shows anything, but for lots of samples this is an empty cluster (meaning there was no problem with the time channel).

**Comment by gfinak** [comment]
`GatingSet2FlowJo` is not guaranteed to produce a workspace that can be read by `parseWorkspace()`. That was never the goal.

**Comment by gfinak** [comment]
Can you produce a minimal reproducible example? Using some other data?

**Comment by mehrnoushmalek** [comment]
```
library(flowCore)
library(flowWorkspace)
#> Loading required package: ncdfFlow
#> Loading required package: RcppArmadillo
#> Loading required package: BH
library(CytoML)
data(GvHD)
fs<-GvHD[1:3]
gs <- GatingSet(fs)
#> .
#> ..done!
biexpTrans <- flowJo_biexp_trans(channelRange=4096, maxValue=262144, pos=4.5,neg=0, widthBasis=-10)
transList <- transformerList(colnames(fs[[1]])[3:6], biexpTrans)
gs<-transform(gs,transList)

fs_trans<- getData(gs)

###Adding the cluster
clean.inds <- lapply(1:length(fs_trans), function(i1) return(list(ind=which(exprs(fs_trans[[i1]])[,"Time"]>793))))
clean.clust <- lapply(1:length(fs_trans), function(x){
  vec<-rep(0,nrow(fs_trans[[x]]))
  if (length(clean.inds[[x]]$ind)>0)
  {
    
    vec[clean.inds[[x]]$ind]<-1
  }
  # }else{
  #   vec[[1]]<-1
  # }
  vec <- as.factor(vec)
  levels(vec) <- c("0", "1")
  return(vec)
})
names(clean.clust)<-sampleNames(fs_trans)

add(gs,clean.clust, parent="root",name = "Clean")
#> NULL
recompute(gs)
#> ...done!

#add one gate
rg <- rectangleGate("FSC-H"=c(200,400), "SSC-H"=c(250, 400),
                    filterId="rectangle")

nodeID<-add(gs, rg,parent="Clean_0")#it is added to root node by default if parent is not specified
#> replicating filter 'rectangle' across samples!
nodeID
#> [1] 4
getNodes(gs[[1]]) #the second population is named after filterId of the gate 
#> [1] "root"               "/Clean_0"           "/Clean_1"          
#> [4] "/Clean_0/rectangle"
recompute(gs)
#> ...done!
#add a quadGate
qg <- quadGate("FL1-H"=2, "FL2-H"=4)
nodeIDs<-add(gs,qg,parent="rectangle")
#> replicating filter 'defaultQuadGate' across samples!
recompute(gs)
#> ...done!
library(CytoML)
GatingSet2flowJo(gs, "/mnt/f/FCS data/Regeneron/Engraftment/TestGatingSet-GVHD/GVHD-Gatingset.wsp")
#> DerivedParameter: /mnt/f/FCS data/Regeneron/Engraftment/TestGatingSet-GVHD/s5a01.Clean.root.EPA.csv
#> DerivedParameter: /mnt/f/FCS data/Regeneron/Engraftment/TestGatingSet-GVHD/s5a02.Clean.root.EPA.csv
#> DerivedParameter: /mnt/f/FCS data/Regeneron/Engraftment/TestGatingSet-GVHD/s5a03.Clean.root.EPA.csv
#> [1] "/mnt/f/FCS data/Regeneron/Engraftment/TestGatingSet-GVHD/GVHD-Gatingset.wsp"

```

**Comment by mehrnoushmalek** [comment]
@gfinak I tested it with not putting children under Clean_0 or Clean_1, and it works just fine:
![clean_0-nochild](https://user-images.githubusercontent.com/2798907/48166760-6ca0fc80-e29e-11e8-875e-ed1ee3f538b8.png)

Or: 
![clean_0-nochild-2](https://user-images.githubusercontent.com/2798907/48166770-762a6480-e29e-11e8-9fd0-d03482468896.png), Unrelated to this, but I think Justin suggested a fix for cases when the gates are no within the same range as the axes ([here](https://github.com/RGLab/CytoML/issues/32))

**Comment by gfinak** [comment]
Thanks. Mike is digging into this.

Greg Finak

**Comment by mikejiang** [comment]
The data set `GvHD` has some special encoded strings in its keywords, which prevents it from being parsed properly (either by flowJo or `flowWorkspace`). I've pushed this fix b35144d086dcbc49ba25b4df260babd6030b72fb and gates show up for me in flowJo now.
Again, `parseWorkspace` will still skip any gates (and its descendants ) that are associcated with `derived-parameter`, which leads to an empty `GatingSet` when you try to parse it back.

**Comment by mehrnoushmalek** [comment]
@mikejiang  I installed 1.9.1 of CytoML and updated flowWorkspace, but still have the same issue when a cluster is used as a parent population. Exactly like the screenshots above, a gate on an empty plot.

**Comment by mikejiang** [comment]
Do you have reproducible example? The one with `GvHD` works just fine for me

**Comment by mehrnoushmalek** [comment]
So I checked the ```*EPA.csv```, that ```gatingSet2flowJo``` created.  I have 0, 1, and 2.
I checked, and  1 corresponds to 0 in the clean.clust, and 2 to 1. 0s are the cells that are not in the parent population of clean.clust (which for my case would be non-singlet cells, as singlets are the parent population for clean.clust).

**Comment by mehrnoushmalek** [comment]
I can try to do this on a public data, and share it with you.

**Comment by mehrnoushmalek** [comment]
Ok, so I just used a random data from flowRepository, and I still get 0 cells inside my gates.
I have the code [here](https://github.com/mehrnoushmalek/Test-CytoML)

**Comment by mikejiang** [comment]
It still works for me
```r
> packageVersion("flowWorkspace")
[1] ‘3.31.2’
> packageVersion(c("CytoML"))
[1] ‘1.9.1’
```
![image](https://user-images.githubusercontent.com/1385649/48290715-ae5dae80-e428-11e8-9ead-afcc6a7dbbcc.png)
I am using flowJo 10.5.2

**Comment by mikejiang** [comment]
The sample name prefixed in your `csv` file names look to be inconsistent with the actual FCS filenames. Are you sure these are correct files exported by `GatingSet2flowJo` for this particular data set?

**Comment by mehrnoushmalek** [comment]
Yes, you used the old data I put on my github, I changed it to another data, I tried it on 3 different datasets, and still my gates are empty. It doesn't seem that my factor is wrong as you reproduced it and it worked.
My csv files derived from``` gatingSet2flowJo``` have the the FCS file name plus ```.fcs.clean.MArgin.EPA.csv``` suffix.

**Comment by mikejiang** [comment]
Try my exported wsp and csv  
[test.zip](https://github.com/RGLab/flowWorkspace/files/2569959/test.zip)
to see if they can be loaded properly in your flowJo

**Comment by mehrnoushmalek** [comment]
I tested yours and I got a warning that the wsp was created with a newer version of flowJo, and here's what I see:
![mike-wsp](https://user-images.githubusercontent.com/2798907/48428065-0c3b1080-e71f-11e8-8e72-82b14594e4b2.png)

The counts and freqs are all 0 from the begining, and gates are empty.
When I open mine, it shows the count, but as soon as I clock on the population everything turns to 0 and gates will be empty as well:
![mmalek-wsp](https://user-images.githubusercontent.com/2798907/48428037-ff1e2180-e71e-11e8-8705-a6d2083e6b3e.png)

Here's my wsp: [Test-MMalek.zip](https://github.com/mehrnoushmalek/Test-CytoML/blob/master/Test-MMalek.zip)

**Comment by mikejiang** [comment]
@gfinak, thanks. @mehrnoushmalek , I can open your wsp and display gates and data without problems.

**Comment by gfinak** [comment]
I'm a bit behind the curve here, but the wsp mentions two fcs files that are not in the archive. Where are these located?

**Comment by mehrnoushmalek** [comment]
I had the data uploaded on our cloud server ([here](https://cloud.bccrc.ca/s/Xr4N4epSaQ9Npbg)) but ended up using another experiment. Mike should have access to those files.

**Comment by mehrnoushmalek** [comment]
@mikejiang, so it doesn't work with flowJo older versions. Our collaborators tried it on Mac 10.5.3, and the whole workspace was empty. It didn't even show the population name.
It would be helpful to have it in the vignette, that CytoML with the clustering parameters only works for specific versions.

**Comment by gfinak** [comment]
I can also see the gates. I'm using FlowJo 10.5.0

**Comment by gfinak** [comment]
What version are you using, @mehrnoushmalek ?

**Comment by mehrnoushmalek** [comment]
@gfinak On windows or Mac?
All of my screenshot is based on 10.0.8.

**Comment by gfinak** [comment]
I'm on a Mac.

**Comment by gfinak** [comment]
And I can confirm that it does NOT work on 10.2 on Mac.

**Comment by mehrnoushmalek** [comment]
I will check if I can install the newer version, and check these wsps, but it seems that the problem is with flowJo version.

**Comment by mehrnoushmalek** [comment]
@gfinak I installed flowJo 10.5.3 and the test data works. However if I run the exact same code on another data, my workspace would be empty with cluster indices, and opens just fine if I don't use cluster indices.  It's really weird, and I don't why it happens, do you have any idea that some FCS file formats might not work with cluster indices ( ```*Margin.EPA.csv``)?

FCS version for the test data ( the one you have access to) is 3.1 , and my other data is 3.

**Comment by mikejiang** [comment]
Again ,you need to or does to the data that can reproduce the same issue you observe in order for us to troubleshoot

**Comment by mehrnoushmalek** [comment]
@mikejiang  and @gfinak  I think I figured out the problem.
It's a space issue in the FCS file name!

**Comment by mikejiang** [comment]
I will have to figure out how flowJo handles this when creating csv files

**Comment by mehrnoushmalek** [comment]
I can rename the files in my code for now. 
I still think it would be good to have a note that csv files won't work with older version of flowJo, so users make sure to have newer versions of flowJo (I think >10.5.0).

**Comment by mikejiang** [comment]
Can you try to use `Plugins` in flowJo to create derived parameters and export the workspace to see how flowJo name these csv files? The `Plugins` somehow stop working in my flowJo.

**Comment by mehrnoushmalek** [comment]
Unfortunately, the computer I'm using flowJo doesn't have R ( public computer for students), so can't  install anything on it or check the plugins.
But I'm pretty sure, flowJo had issue with spaces in file name or file path, (we had the same issue when we created some plugins), unless they have changed that very recently. you can confirm this with Josef.

**Comment by mikejiang** [comment]
You are right. flowJo doesn't like the spaces. I've verified.
 ping @jspidlen

**Comment by jspidlen** [comment]
Hi guys,

- Most R-based plugins are using R CMD BATCH "some script" under the hood. 
- A few R-based plugins are using Rscript "some script" under the hood.
- The path to "some script" is typically derived from the location where you save your .wsp file.
- Many R versions do not work with R CMD BATCH "some script" if there is a space in the path to "some script" (even if the path is properly enclosed in quotes etc.). Based on my testing, this was the case for R 3.5.0 and many older versions on Windows (e.g., https://stackoverflow.com/questions/48544345/rscript-file-path-with-space), but fixed in R 3.5.1, and many R versions on OSX.
- Rscript "some script" does not have this problem.

As far as FlowJo's R-based plugins go:
- Those that are based on Rscript are fine (but that's just like 1 or 2). 
- Those that are based on R CMD BATCH on Windows, you will need R 3.5.1 to make it work, and you may want to use FlowJo 10.5.2 or later to make sure everything is enclosed in proper quotes (FlowJo 10.5.2 is also a bit smarter in searching for R if the path is not set in user preferences). 
- Those that are based on R CMD BATCH on OSX, you will need FlowJo 10.5.2 or later, which has a workaround for the space bug in R (it creates a symbolic link to the "some script" in a temp directory so that there is no space in the path, and then it executes the R CMD BATCH "/path/to/symlink" instead of R CMD BATCH "some script".

Let me know if there is anything else I can do to help or clarify.
Best, Josef
