### ISSUE TITLE
Subsetting a gatingSet and exporting the result.

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/flowWorkspace#290]
Hello,

With older version of flowWorkspace, and CytoML, I was able to just do:
`gs2 <- gs[1:3]
GatingSet2flowJo(gs2,outFile)
 `
But it doesn't work with the new version, and I get an error of : 
`Error in pData(gs)[["PID"]] : subscript out of bounds
In addition: Warning messages:
1: In if (nchar(object@name) > 0) { :
  the condition has length > 1 and only the first element will be used
2: In if (nchar(object@name) > 0) { :
  the condition has length > 1 and only the first element will be used`
When I look at `pData(gs)` and `pData(gs2)`, and `gs2@data@phenoData@data`, they don't seem to be properly set.
I've also tried :
`gs2<- subset(gs, name %in% sample.names))`, and still no luck.

**Comment by jacobpwagner** [comment]
@mehrnoushmalek, this is likely related to an issue that was fixed just a few days ago in https://github.com/RGLab/flowWorkspace/commit/24c6535e7cfacf357a3f371c5ee4dded50bbf757. Will you please try pulling the most recent version, re-installing, and then trying again? Please let me know if that still doesn't fix it and I'll see if there may be some other issue.

**Comment by mehrnoushmalek** [comment]
> @mehrnoushmalek, this is likely related to an issue that was fixed just a few days ago in [24c6535](https://github.com/RGLab/flowWorkspace/commit/24c6535e7cfacf357a3f371c5ee4dded50bbf757). Will you please try pulling the most recent version, re-installing, and then trying again? Please let me know if that still doesn't fix it and I'll see if there may be some other issue.


Thanks for the reply @jacobpwagner .
I installed the trunk version (3.33.7, version number wasn't bumped I guess). 
If I do the `gs2 <- gs[1:3]`, I still get the error of:
`Error in pData(gs)[["name"]] : subscript out of bounds`, but the warnings are gone.

**Comment by jacobpwagner** [comment]
I'm looking in to it. I can't reproduce the error yet, but it would help a lot if you could provide the traceback from the error and maybe the code and data bringing about the error. Also, if you could add your sessionInfo so I can check package versions, that would help as well.

**Comment by jacobpwagner** [comment]
It seems strange that the error changed to a missing "name" column now (while it was "PID" before). This is likely coming from line 51 in `GatingSet2flowJo.R`, which should only fail if the `data.frame` returned by `pData(gs)` is missing a "name" column. What is the output of `colnames(pData(gs))` and `colnames(pData(gs2))`?

**Comment by mehrnoushmalek** [comment]
`colnames(pData(gs))
[1] "name"
colnames(pData(gs2))
NULL`

**Comment by mehrnoushmalek** [comment]
Here is an example: 
`fcs.loc <- system.file("extdata",package="flowCore")
 file.location <- paste(fcs.loc, dir(fcs.loc), sep="/")
 fs <- read.flowSet(file.location[1:3])
gs <- GatingSet(fs)
lgcl <- estimateLogicle(gs[[1]],colnames(fs)[3:7])
gs <- transform(gs, lgcl)
    
    
#add one gate
    rg <- rectangleGate("FSC-H"=c(200,400), "SSC-H"=c(250, 400),
        filterId="rectangle")
    
    nodeID<-gs_pop_add(gs, rg)#it is added to root node by default if parent is not specified
    nodeID
    gs_get_pop_paths(gs[[1]]) #the second population is named after filterId of the gate 
    
#add a quadGate
    qg <- quadGate("FL1-H"=2, "FL2-H"=4)
    nodeIDs<-gs_pop_add(gs,qg,parent="rectangle")
    nodeIDs #quadGate produces four population nodes

gatingset_to_flowjo(gs,OutFile)
#Works fine
gs2 <- gs[1:2]
gatingset_to_flowjo(gs2, OutFile)
Error in pData(gs)[["name"]] : subscript out of bounds

`

**Comment by jacobpwagner** [comment]
Okay, thanks. I think I may see the problem. I'll work on it and get a fix up soon.

**Comment by jacobpwagner** [comment]
Alright, https://github.com/RGLab/flowWorkspace/commit/03cf2af83fd3bc88cd48c1b6be64bd3639920ef1 should fix it. Let me know if there's still an issue, but that was almost definitely the cause of your error. Thanks @mehrnoushmalek for pointing this out. It came down to simply forgetting a `drop=FALSE` in the `pData` accessor for `GatingSet`.

**Comment by mehrnoushmalek** [comment]
@jacobpwagner  Thank you Jacob for the quick fix, I really appreciate it.
I just tested it and it works perfectly fine. Is it possible that you can help with [this]? :-)(https://github.com/RGLab/CytoML/issues/60)

**Comment by jacobpwagner** [comment]
Yeah, let me take a look at it. I'll close this and continue discussion over on that issue.

**Comment by mehrnoushmalek** [comment]
Here's the example with the same file, I tested it and it seems to work:
`fcs.loc <- system.file("extdata",package="flowCore")

file.location <- paste(fcs.loc, dir(fcs.loc), sep="/")
fs.raw <- read.flowSet(file.location[1:3])
gs <- GatingSet(fs.raw)
lgcl <- estimateLogicle(gs[[1]],colnames(fs)[3:7])
gs <- transform(gs, lgcl)
recompute(gs)
fs.tr <- gs_pop_get_data(gs)
clean.inds <- fsApply(fs.tr,function(f){
  message(paste("","Cleaning over time",sep="\n"))
  segment<-ceiling(nrow(f)/12)
  output.path <- getwd()
  cleaned <- flowCut(f, Segment = segment,Directory = output.path,PrintToConsole=F,
                     FileID = identifier(f), Plot ="None",Verbose = T,UseCairo = F)
  return(cleaned)
})
names(clean.inds)<- sampleNames(fs)

clean.clust <- lapply(1:length(clean.inds), function(x){
  vec<-rep(0,nrow(fs.tr[[x]]))
  if (length(clean.inds[[x]]$ind)>0)
  {
    
    vec[clean.inds[[x]]$ind]<-1
  }
  
  vec <- as.factor(vec)
  levels(vec) <- c("0", "1")
  return(vec)
})
names(clean.clust)<-sampleNames(fs)

gs_pop_add(gs,clean.clust,parent = "root", name = "Clean")
recompute(gs)

rg <- rectangleGate("FSC-H"=c(200,400), "SSC-H"=c(250, 400),
                    filterId="rectangle")
nodeID<-gs_pop_add(gs, rg,parent = "Clean_0")
gs_get_pop_paths(gs[[1]]) 
#add a quadGate
qg <- quadGate("FL1-H"=2, "FL2-H"=4)
nodeIDs<-gs_pop_add(gs,qg,parent="rectangle")
gatingset_to_flowjo(gs, outFile =paste(output.path,"test.wsp",sep="/))
ws <- tryCatch(open_flowjo_xml(paste(output.path,"test.wsp",sep="/)),error=function(x) {return(1)})
tmp <- fsApply(fs.raw, function(x) write.FCS(x, paste0(output.path,identifier(x),".fcs")))
G <- tryCatch(flowjo_to_gatingset(ws,path ="/home/rstudio/results/",
                            ,name = 1),error=function(x) {return(1)})`
Now when you plot the gatingSet to see the gatingHierarchy, you only see the root node, which is different from the `gs` gatinghierarchy.
`plot(G[[1]])`

`plot(gs[[1]])`

**Comment by mehrnoushmalek** [comment]
I just noticed, that after subsetting, the `length` function gives the gs length, not gs2.

**Comment by jacobpwagner** [comment]
The length issue is fixed by https://github.com/RGLab/flowWorkspace/commit/de30531df47b3fadafa906a2681cf5837e820000. It should have been included in an earlier commit. My apologies.
